### ISSUE TITLE
Infinite Loop of Update Alert

### ISSUE THREAD

**Issue by need2edit** [ArtSabintsev/Siren#126]
We've recently updated our app, distributed through the app store. Today we started seeing the "new version is available alert", but when the user taps update, and they are taken to the store, the system already has installed the latest version. Tapping "Open" takes you back to the app, and the alert appears again.  So an infinite loop

in didFinishLaunchingWithOptions we have this set to ".immediately", in other areas we have it set to daily.

Any guidance would be appreciated here.

**Comment by getaaron** [comment]
Sounds like a possible duplicate of https://github.com/ArtSabintsev/Siren/issues/120 — the iTunes API reports a new version is available, but the user's App Store cache doesn't have it yet. If this is the issue, it's frustrating but usually clears up in 24 hours.

**Comment by ArtSabintsev** [comment]
Definitely a dupe. I need to bring in this PR soon (https://github.com/ArtSabintsev/Siren/pull/124) to avoid this issue.

**Comment by ArtSabintsev** [comment]
@need2edit What people usually do to get around this issue is they have Siren be driven by a server-side configuration file that enables/disables Siren remotely. 

Obviously, this isn't ideal, but this is the downside of the Apple's APIs updating faster than the apps getting propagated to the CDNs.

Closing this issue, but feel free to respond.

**Comment by ArtSabintsev** [comment]
Hey - just wanted to let you know that this issue has been fixed as of v2.0.0: https://github.com/ArtSabintsev/Siren/releases/tag/2.0.0

**Comment by iOSDias** [comment]
The issue has not been already fixed, I use version 2.0.8 and I have the same issue - After updating app through App Store when user open it, the alert still shows but app has the latest version. After tapping update button and entering to Appstore there is just open button.

**Comment by need2edit** [comment]
Thank you @ArtSabintsev sorry I didn't respond earlier on! Didn't see this issue in our last 2 deployments which had 3.2.0. Thanks again!

**Comment by danielchangsoojones** [comment]
I am still having this problem. I am on version 3.2.0, and I have not set any showAlertAfterCurrentVersionHasBeenReleasedForDays . Therefore, it should be defaulting to 1 day. However, I still have some users where it tells them to update and then they go the store and it says open because they already seem to have the most updated version.

**Comment by ArtSabintsev** [comment]
Please open a new issue, and provide your bundle ID. 

Going to lock this issue to avoid pinging people who no longer have this issue.
