### ISSUE TITLE
Set 'presentingViewController' before calling checkVersion Error

### ISSUE THREAD

**Issue by liebeskind** [ArtSabintsev/Siren#20]
I am using Siren 0.3.5 via CocoaPods 0.37.2 and am getting the error 

*"Please make sure that you have set 'presentingViewController' before calling checkVersion."*

Have tried running from AppDelegate and from a UIViewController.  I've tried setting the following in the UIViewController code:

    siren.sharedInstance().presentingViewController = self

but getting nil when unwrapping Optional in
    
    func sirenBundlePath() -> String {
        return NSBundle.mainBundle().pathForResource("Siren", ofType: "bundle") as String!
    }

**Comment by ArtSabintsev** [comment]
Hi @liebeskind,

Please upgrade to Siren 0.4.0, remove the `presentingViewController` code, and make sure you have `Siren.bundle` in your project.

That should fix the issue :)

**Comment by ArtSabintsev** [comment]
I realized I forgot to push 0.4.0 to CocoaPods. Just did it - try again :)

**Comment by liebeskind** [comment]
Thanks - was still getting the same error when upgraded to 0.4.0 through CocoaPods and removed reference to presentingViewController

Fixed the issue by adding Siren.bundle to **Build Phases > Copy Bundle Resources** within my primary xcode project.

**Comment by ArtSabintsev** [comment]
Awesome - glad it's working now. 0.4.0 deprecated the `presentingViewController` variable due to a change made on how the alert is being presented. 

Enjoy!
