### ISSUE TITLE
iOS 13, alert appears but immediately disappears

### ISSUE THREAD

**Issue by mmdock** [ArtSabintsev/Siren#305]
# If you're experiencing a problem integrating Siren into your app, please provide the following information when posting a new issue:

- **Are you using the [latest version](https://github.com/ArtSabintsev/Siren/releases) of Siren?**:  yes.
- **What is your app's Bundle ID?**: 
com.dattch.dattch
- **When was the latest version of your app published to the App Store?**: 
August 26th
- **Is your app published in the US App Store? If not, what App Store is it published in?**:
yes
- **Does Siren work if you plugin your app's `BundleID` (and `countryCode`, if necessary) into the Example app?**: haven't checked.

---

So, the alert will briefly appear, but then immediately disappear.  I checked this on iOS 13 simulator and compared behavior to iOS 12 behavior.

Tried on Siren 5.1.2 (version i was updating to) and Siren version 4.2.2 updating from.  

I am in the process of updating my app for some iOS 13 changes and notices this behavior.

**Comment by ArtSabintsev** [comment]
Hi, known issue, but a beta is a beta, and I have yet to figure this one out. I think I saw it working fine on a device. Can you test that out?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
I have a PR opened for swift5.1 changes here: https://github.com/ArtSabintsev/Siren/pulls

I still do not have a fix for the flickering issue, but you can track that branch or submit a PR against it if you figure it out.

**Comment by mmdock** [comment]
@ArtSabintsev Verified it occurs on my device as well.  I couldn't test on a iOS 13 device, only my 13.1 since that's all i have for physical device testing atm.  I haven't read up much on iOS 13 changes, but could this be a result of Apple adding the Scene based lifecycle?  Just a random thought.  Nothing really to back that up - just throwing a dart.

**Comment by ArtSabintsev** [comment]
Yup, that’s my thought as well. Will check it out soon!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maasim94** [comment]
this issue is solved? 
tested on siren v 5.1 same thing happening

**Comment by moesalih** [comment]
@ArtSabintsev This is still a problem. Any update? Why is this issue closed?

**Comment by ArtSabintsev** [comment]
CocoaPods should be installing 5.2.1. Are you still seeing this issue as of today when you do a pod update?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmdock** [comment]
mine installs 5.2.1 successfully without needed the extra pointing

**Comment by ArtSabintsev** [comment]
Ok, so there is no issue. Locking this issue to avoid pinging me unnecessarily. If a similar issue persists, please open a new ticket.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
